DROP TABLE LEKARZ;
DROP TABLE ZARAZONY;
DROP TABLE ZMARLY;
DROP TABLE SZPITAL;
DROP TABLE TESTNACOVID;
DROP TABLE SZPITALRODZAJ;
DROP TABLE SPECJALIZACJA;
DROP TABLE RODZAJTESTU;
DROP TABLE DANEOSOBOWE;
DROP TABLE ADRES;
DROP TABLE MIASTO;
DROP TABLE WOJEWODZTWO;
COMMIT;


